version: "3"

services:
  app:
    build: ./Dockerimages_1/app
    image: ohjiwon1214/app:latest
    ports:
      - "8000:80"
# Dockerfile이 프로젝트 루트가 아닌 Dockerimages/app 폴더에 위치하여 빌드 경로 수정
# 내부 웹서버 포트가 80이므로 로컬 접속 편의를 위해 8000:80으로 변경